### ISSUE TITLE
On-startup "js page" commands don't run

### ISSUE THREAD

**Issue by anko** [uzbl/uzbl#284]
If I put this at the end of my config file—

```
uri about:blank
js page string "document.write('hello')"
```

—I'd expect uzbl-browser to start on the page `about:blank` and to display the string "hello" as the page content. Instead, I get an all-white blank page, no text.

It works if I load the page and type in `:` followed by the above `js` command myself.

What's up with that?

Previously in the uzbl version that Arch Linux calls `uzbl-browser-2012.05.14-3-x86_64`, a similar line worked. It was great for setting `about:blank`'s background to a hacker-cave-friendlier `#000000`.

- - -

`uzbl-core --bug-info`:

```
Commit: UNKNOWN
GTK compile: 3.20.3
GTK run: 3.20.4
WebKit compile: 2.4.11
WebKit run: 2.4.11
WebKit2: 0
libsoup compile: 2.54.0
libsoup run: 2.54.1
```

**Comment by keis** [comment]
Most likely what's going on here is that the page load of `about:blank` has not finished before the javascript tries to execute. I can't confirm that though because putting just that as my config works for me.

In general you want to run javascript on the `LOAD_FINISH` event, but in this case of running js as part of the "home page" the easy solution in simply to drop the `uri about:blank` line completly

**Comment by anko** [comment]
Indeed, using only the `js` line gets the intended result. Thanks!
